server:
  port: 8080

  #Hibernate
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demoShop?createDatabeseIfNotExist=true
    username: root
    password: root

    #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect